import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AppNavigation from "@/components/app-navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="flex justify-between bg-black text-white p-4">
            <h1>IZAM</h1>
            <div className="flex gap-4 items-center">
              <h3>HOME</h3>
              <h3>JOBS</h3>
            </div>
          </div>
        </header>

        <div className="flex h-[calc(100vh-56px)] p-4 flex-col md:flex-row">
          <AppNavigation />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
